shrine-timeout: 60
shrine-max-distance: 15
animation:
  ticks-between-refreshes: 5
  degrees-per-second: 45

shrines:
- design: example
  recipes:
  - in:
    - STICK
    - material: COBBLESTONE
      amount: 64
    out:
      material: STONE
      name: poop
      lore:
        - a
        - poop
        - sir
      customModel: 11