name: @name@
version: @version@
description: @description@
load: POSTWORLD
api-version: @api@
author: Hugo B.
authors:
  - Matt12

main: @group@.@artifact@.@main@

softdepend:
  - WorldEdit
  - CustomItems

permissions:
  shrinecraft.command:
    description: allows the usage of /shrinecraft
  shrinecraft.command.reload:
    description: allows the reload of ShrineCraft via "/shrinecraft reload"
    children:
      shrinecraft.command: true
  shrinecraft.command.setdesign:
    description: allows to set a design via "/shrinecraft setdesign <design name>"
    children:
      shrinecraft.command: true




